// pagination

const SET_PAGE = "SET_PAGE";
const SET_TOTAL_ITEMS = "SET_TOTAL_ITEMS";
const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";

// items

const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";

// filter

const SET_FILTER = "SET_FILTER";
const CLEAR_FILTER = "CLEAR_FILTER";

export {
  // pagination
  SET_PAGE,
  SET_TOTAL_ITEMS,
  SET_TOTAL_PAGES,
  // items
  FETCH_ITEMS_REQUEST,
  FETCH_ITEMS_SUCCESS,
  FETCH_ITEMS_FAILURE,
  // filter
  SET_FILTER,
  CLEAR_FILTER,
};
